/*
 *    Copyright 2018 Makoto Consulting Group, Inc
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.makotogo.learn.mobile.iot.devicecontroller;

import android.app.Fragment;
import android.content.Context;
import android.os.Build;
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import org.apache.commons.lang3.tuple.Pair;
import org.eclipse.paho.client.mqttv3.MqttMessage;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

/**
 * A fragment representing a list of Items, in this case the Devices that are manged
 * by the Controller Device.
 * <p/>
 * Activities containing this fragment MUST implement the {@link OnDashboardFragmentInteractionListener}
 * interface.
 */
public class DashboardFragment extends Fragment {

    private static final String TAG = DashboardFragment.class.getSimpleName();

    // The Fragment Tag.
    public static final String FRAGMENT_TAG = DashboardFragment.class.getName();

    // Parameter argument names (for access within the Bundle)
    private static final String ARG_COLUMN_COUNT = "arg-column-count";

    // Parameter variables
    private int mColumnCount;
    private OnDashboardFragmentInteractionListener mListener;

    /**
     * Mandatory empty constructor for the fragment manager to instantiate the
     * fragment (e.g. upon screen orientation changes).
     */
    public DashboardFragment() {
    }

    /**
     * Creates a new instance of this Fragment, and initializes its Fragment arguments
     * in the Android approved way.
     *
     * @param columnCount The number of columns to display, where one column is used
     *                    to display a single item from the RecyclerView's Adapter.
     * @return DashboardFragment - the newly created Fragment, ready to be handed over
     * to the FragmentManager.
     */
    public static DashboardFragment newInstance(int columnCount) {
        DashboardFragment fragment = new DashboardFragment();
        Bundle args = new Bundle();
        args.putInt(ARG_COLUMN_COUNT, columnCount);
        fragment.setArguments(args);
        return fragment;
    }

    /**
     * The ubiquitous onCreate() method. Auto-generated by the Wizard. Hey, I just work here.
     *
     * @param savedInstanceState Any previously saved state.
     */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (getArguments() != null) {
            mColumnCount = getArguments().getInt(ARG_COLUMN_COUNT);
        }
        // If running on version < Marshmallow, then the listener has to be initialized this way
        if (Build.VERSION.SDK_INT < 23) {
            Context context = getActivity();
            if (context instanceof DashboardFragment.OnDashboardFragmentInteractionListener) {
                mListener = (DashboardFragment.OnDashboardFragmentInteractionListener) context;
            } else {
                throw new RuntimeException(context.toString()
                        + " must implement OnFragmentInteractionListener");
            }
        }

    }

    /**
     * The ubituious onCreateView method. Auto-generated by the Wizard.
     *
     * @param inflater The Layout inflater
     * @param container Not used
     * @param savedInstanceState Any previously saved state
     *
     * @return The Fragment's view, fully initialized
     */
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        final View view = inflater.inflate(R.layout.fragment_dashboard_list, container, false);
//
        // Subscribe to discovery response messages
        mListener.subscribeToDeviceResponse(JSONDiscoveryDeviceResponse.DISCOVERY.toString(), new DeviceResponseCallback() {
            @Override
            public void onDeviceResponse(MqttMessage deviceResponseMessage) {
                final String METHOD = "onDeviceResponse(): ";
                // Get the response
                String messageAsString = new String(deviceResponseMessage.getPayload());
                // Create a JSON object
                try {
                    createItemsFromJsonMessage(messageAsString);
                    // Set the adapter
                    if (view instanceof RecyclerView) {
                        Context context = view.getContext();
                        RecyclerView recyclerView = (RecyclerView) view;
                        if (mColumnCount <= 1) {
                            recyclerView.setLayoutManager(new LinearLayoutManager(context));
                        } else {
                            recyclerView.setLayoutManager(new GridLayoutManager(context, mColumnCount));
                        }
                        recyclerView.setAdapter(new DashboardRecyclerViewAdapter(IotDeviceContent.ITEMS, mListener));
                    }
                } catch (JSONException e) {
                    // TODO: Store this in Notifications deque
                    String notification = METHOD + "JSONException occurred while creating JSONObject from String: '" + messageAsString + "'";
                    mListener.pushNotification(notification);
                    Log.e(TAG, notification, e);
                }
            }
        });

        // Get the ApplicationClient and broadcast a "discovery" request to
        /// see all of the devices that the Controller device is managing.
        mListener.publishDiscoveryEvent();
        return view;
    }

    /**
     * Take the JSON object (in the form of a String) and transform it into the
     * IotDeviceItem's that will be displayed in the RecyclerView.
     *
     * @param messageAsString The JSON message, as a String (that's how it comes
     *                        from the server)
     *
     * @throws JSONException - If there is a problem processing the message (like
     * an expected element is missing, for example). If you get this exception,
     * the first thing to ask is, "Did I change the JSON format of the message
     * I'm processing?" because that's most likely what has gone wrong.
     */
    private void createItemsFromJsonMessage(String messageAsString) throws JSONException {
        JSONObject jsonObject = new JSONObject(messageAsString);
        jsonObject = jsonObject.getJSONObject(JSONDiscoveryDeviceResponse.D.toString());
        JSONArray devices = jsonObject.getJSONArray(JSONDiscoveryDeviceResponse.DEVICES.toString());
        // Clear out the current collection of IotDeviceItems
        IotDeviceContent.clearAll();
        // Create an IotDeviceItem for each device in the list
        for (int aa = 0; aa < devices.length(); aa++) {
            JSONObject device = devices.getJSONObject(aa);
            // Create the IotDeviceItem
            String deviceId = device.getString(JSONDiscoveryDeviceResponse.DEVICE_ID.toString());
            String deviceDescription = device.getString(JSONDiscoveryDeviceResponse.DESCRIPTION.toString());
            JSONArray actionsJsonArray = device.getJSONArray(JSONDiscoveryDeviceResponse.ACTIONS.toString());
            //
            // Loop through the actions and set them on the IotDeviceContent object
            List<Pair<String, String>> actions = new ArrayList<>();
            for (int bb = 0; bb < actionsJsonArray.length(); bb++) {
                JSONObject action = (JSONObject) actionsJsonArray.get(bb);
                String actionName = action.getString(JSONDiscoveryDeviceResponse.ACTION.toString());
                String actionDescription = action.getString(JSONDiscoveryDeviceResponse.DESCRIPTION.toString());
                actions.add(Pair.of(actionName, actionDescription));
            }
            IotDeviceContent.IotDeviceItem iotDeviceItem =
                    new IotDeviceContent.IotDeviceItem(Integer.valueOf(aa).toString(), deviceId, deviceDescription, actions);
            IotDeviceContent.addItem(iotDeviceItem);
        }
    }

    /**
     * Some initial setup. Mainly to make sure that the Context object (representing
     * the owning Activity most likely) implements the necessary interface so that everything
     * is properly wired up: {@link OnDashboardFragmentInteractionListener}.
     *
     * @param context The application context object - most likely the owning Activity, but
     *                not necessarily. Must implement the required interface(s).
     */
    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof OnDashboardFragmentInteractionListener) {
            mListener = (OnDashboardFragmentInteractionListener) context;
        } else {
            throw new RuntimeException(context.toString()
                    + " must implement OnDashboardFragmentInteractionListener");
        }
    }

    /**
     * Application is detaching. Do some cleanup.
     */
    @Override
    public void onDetach() {
        super.onDetach();
        mListener = null;
    }

    /**
     * This interface must be implemented by activities that contain this
     * fragment to allow an interaction in this fragment to be communicated
     * to the activity and potentially other fragments contained in that
     * activity.
     * <p/>
     * See the Android Training lesson <a href=
     * "http://developer.android.com/training/basics/fragments/communicating.html"
     * >Communicating with Other Fragments</a> for more information.
     */
    public interface OnDashboardFragmentInteractionListener {

        /**
         * Tell the owning Activity that the user has pressed an item
         * in the RecyclerView.
         *
         * @param item The item that was pressed
         */
        void onDashboardFragmentInteraction(IotDeviceContent.IotDeviceItem item);

        /**
         * Asks the context (through this interface) to publish the discovery event,
         * whose response contains the devices that are under management so they
         * can be displayed in this Fragment's view.
         */
        void publishDiscoveryEvent();

        /**
         * Asks the context (through this interface) to subscribe to any responses
         * from the Controller device for the specified response event. Awaits a
         * response (which comes from the underlying middleware's thread) through
         * the {@link DeviceResponseCallback}. No UI Thread cycles used!
         *
         * @param deviceResponse The device response event to which to subscribe
         *
         * @param deviceResponseCallback The callback where the response is processed.
         *                               Will be done on the middleware thread so the
         *                               UI Thread is not used (to prevent ANRs and other
         *                               nasty Android hobgobblins).
         */
        void subscribeToDeviceResponse(String deviceResponse, DeviceResponseCallback deviceResponseCallback);

        /**
         * Pushes the specified notification message onto the Notifications deque
         *
         * @param notificationMessage Duh
         */
        void pushNotification(String notificationMessage);

    }
}
